### ISSUE TITLE
make-a-course link does not work

### ISSUE THREAD

**Issue by jeremyabramson** [RunestoneInteractive/HomePage#2]
[](http://runestoneinteractive.org/customcourse.html is dead.)

**Comment by bnmnetp** [comment]
Where did you find that link?  The place to create a course is on https://runestone.academy

**Comment by jeremyabramson** [comment]
> Where did you find that link? The place to create a course is on https://runestone.academy
> 
> If you are looking for documentation to get started creating your own course, please have a look at: https://runestone.academy/runestone/static/instructorguide/index.html

The make-a-course link [that is dead] is from the URL you mentioned above. =]

**Comment by bnmnetp** [comment]
Thanks. I've cleared out that dead link.  The video below that link is better than what was on that page, and the materials are in chapter 4 of the guide.
